### ISSUE TITLE
Minor build issues with v2.0.0

### ISSUE THREAD

**Issue by anshumang** [milakov/nnForge#26]
I am building on an Ubuntu 14.04 box. 
gcc  4.8.4
boost 1.54.0
opencv 2.4.8
protobuf 8.0.0

MATIO and NETCDF disabled
CUDA enabled

Had to set CPP11COMPILER to yes from no(default). The first C++11 failure starts from nnforge/data_visualizer.cpp

Build of nnforge/plain fails for not finding memcpy starting with nnforge/plain/dropout_layer_tester_plain.cpp
Fixed by including <cstring> in nnforge/layer.h

cuDNN distributions now have inc/ and lib64/ so includes like <cudnn.h> fail with the current Settings.mk. Copying /usr/local/cuDNN/inc/cudnn.h and /usr/local/cuDNN/lib64/libcudnn.so to directly under /usr/local/cuDNN is one possible fix.

Otherwise builds fine. :+1: for an awesome new release !

**Comment by anshumang** [comment]
Hm...the build fails for the cuda backend. Log below -
nvcc -c sigmoid_partial_layer_tester_cuda.cu -use_fast_math -DBOOST_NOINLINE='__attribute__ ((noinline))' -g -lineinfo -Xcompiler="-I/usr/lib/x86_64-linux-gnu/include -I/usr/lib/x86_64-linux-gnu/include -I/usr/local/cuda/include -I/usr/local/cuDNN -I/usr/lib/x86_64-linux-gnu/include -ffast-math -march=native  -mfpmath=sse -msse2  -g" -DNNFORGE_CPP11COMPILER -std=c++11 -gencode=arch=compute_30,code=sm_30 -gencode=arch=compute_35,code=\"sm_35,compute_35\" -o sigmoid_partial_layer_tester_cuda.o
sigmoid_partial_layer_tester_cuda.h(36): error: identifier "const_cuda_linear_buffer_device_smart_ptr" is undefined

sigmoid_partial_layer_tester_cuda.h(37): error: identifier "const_cuda_linear_buffer_device_smart_ptr" is undefined

sigmoid_partial_layer_tester_cuda.h(38): error: identifier "const_cuda_linear_buffer_device_smart_ptr" is undefined

sigmoid_partial_layer_tester_cuda.h(39): error: identifier "cuda_linear_buffer_device_smart_ptr" is undefined

sigmoid_partial_layer_tester_cuda.h(40): error: identifier "cuda_linear_buffer_device_smart_ptr" is undefined

sigmoid_partial_layer_tester_cuda.cu(63): error: identifier "const_cuda_linear_buffer_device_smart_ptr" is undefined

sigmoid_partial_layer_tester_cuda.cu(64): error: identifier "const_cuda_linear_buffer_device_smart_ptr" is undefined

sigmoid_partial_layer_tester_cuda.cu(65): error: identifier "const_cuda_linear_buffer_device_smart_ptr" is undefined

sigmoid_partial_layer_tester_cuda.cu(66): error: identifier "cuda_linear_buffer_device_smart_ptr" is undefined

sigmoid_partial_layer_tester_cuda.cu(67): error: identifier "cuda_linear_buffer_device_smart_ptr" is undefined

sigmoid_partial_layer_tester_cuda.cu(72): error: identifier "input_elem_count_per_feature_map" is undefined

/usr/include/c++/4.8/bits/ptr_traits.h(124): error: incomplete type is not allowed
          detected during:
            instantiation of class "std::__ptrtr_pointer_to<_Ptr> [with _Ptr=<error-type>]" 
(137): here
            instantiation of class "std::pointer_traits<_Ptr> [with _Ptr=<error-type>]" 
/usr/include/c++/4.8/bits/alloc_traits.h(109): here
            instantiation of class "std::allocator_traits<_Alloc> [with _Alloc=std::allocator<<error-type>>]" 
/usr/include/c++/4.8/ext/alloc_traits.h(123): here
            instantiation of class "__gnu_cxx::__alloc_traits<_Alloc> [with _Alloc=std::allocator<<error-type>>]" 
/usr/include/c++/4.8/bits/stl_vector.h(75): here
            instantiation of class "std::_Vector_base<_Tp, _Alloc> [with _Tp=<error-type>, _Alloc=std::allocator<<error-type>>]" 
/usr/include/c++/4.8/bits/stl_vector.h(210): here
            instantiation of class "std::vector<_Tp, _Alloc> [with _Tp=<error-type>, _Alloc=std::allocator<<error-type>>]" 
sigmoid_partial_layer_tester_cuda.cu(77): here

/usr/include/c++/4.8/bits/ptr_traits.h(142): error: incomplete type is not allowed
          detected during:
            instantiation of class "std::pointer_traits<_Ptr> [with _Ptr=<error-type>]" 
/usr/include/c++/4.8/bits/alloc_traits.h(109): here
            instantiation of class "std::allocator_traits<_Alloc> [with _Alloc=std::allocator<<error-type>>]" 
/usr/include/c++/4.8/ext/alloc_traits.h(123): here
            instantiation of class "__gnu_cxx::__alloc_traits<_Alloc> [with _Alloc=std::allocator<<error-type>>]" 
/usr/include/c++/4.8/bits/stl_vector.h(75): here
            instantiation of class "std::_Vector_base<_Tp, _Alloc> [with _Tp=<error-type>, _Alloc=std::allocator<<error-type>>]" 
/usr/include/c++/4.8/bits/stl_vector.h(210): here
            instantiation of class "std::vector<_Tp, _Alloc> [with _Tp=<error-type>, _Alloc=std::allocator<<error-type>>]" 
sigmoid_partial_layer_tester_cuda.cu(77): here

/usr/include/c++/4.8/bits/ptr_traits.h(63): error: name followed by "::" must be a class or namespace name
          detected during:
            instantiation of class "std::__ptrtr_diff_type<_Tp, <unnamed>> [with _Tp=<error-type>, <unnamed>=<error-constant>]" 
(144): here
            instantiation of class "std::pointer_traits<_Ptr> [with _Ptr=<error-type>]" 
/usr/include/c++/4.8/bits/alloc_traits.h(109): here
            instantiation of class "std::allocator_traits<_Alloc> [with _Alloc=std::allocator<<error-type>>]" 
/usr/include/c++/4.8/ext/alloc_traits.h(123): here
            instantiation of class "__gnu_cxx::__alloc_traits<_Alloc> [with _Alloc=std::allocator<<error-type>>]" 
/usr/include/c++/4.8/bits/stl_vector.h(75): here
            instantiation of class "std::_Vector_base<_Tp, _Alloc> [with _Tp=<error-type>, _Alloc=std::allocator<<error-type>>]" 
/usr/include/c++/4.8/bits/stl_vector.h(210): here
            instantiation of class "std::vector<_Tp, _Alloc> [with _Tp=<error-type>, _Alloc=std::allocator<<error-type>>]" 
sigmoid_partial_layer_tester_cuda.cu(77): here

/usr/include/c++/4.8/bits/ptr_traits.h(147): error: incomplete type is not allowed
          detected during:
            instantiation of type "std::pointer_traits<_Ptr>::rebind<const <error-type>> [with _Ptr=<error-type>]" 
/usr/include/c++/4.8/bits/alloc_traits.h(109): here
            instantiation of class "std::allocator_traits<_Alloc> [with _Alloc=std::allocator<<error-type>>]" 
/usr/include/c++/4.8/ext/alloc_traits.h(123): here
            instantiation of class "__gnu_cxx::__alloc_traits<_Alloc> [with _Alloc=std::allocator<<error-type>>]" 
/usr/include/c++/4.8/bits/stl_vector.h(75): here
            instantiation of class "std::_Vector_base<_Tp, _Alloc> [with _Tp=<error-type>, _Alloc=std::allocator<<error-type>>]" 
/usr/include/c++/4.8/bits/stl_vector.h(210): here
            instantiation of class "std::vector<_Tp, _Alloc> [with _Tp=<error-type>, _Alloc=std::allocator<<error-type>>]" 
sigmoid_partial_layer_tester_cuda.cu(77): here

/usr/include/c++/4.8/bits/ptr_traits.h(147): error: incomplete type is not allowed
          detected during:
            instantiation of type "std::pointer_traits<_Ptr>::rebind<void> [with _Ptr=<error-type>]" 
/usr/include/c++/4.8/bits/alloc_traits.h(120): here
            instantiation of class "std::allocator_traits<_Alloc> [with _Alloc=std::allocator<<error-type>>]" 
/usr/include/c++/4.8/ext/alloc_traits.h(123): here
            instantiation of class "__gnu_cxx::__alloc_traits<_Alloc> [with _Alloc=std::allocator<<error-type>>]" 
/usr/include/c++/4.8/bits/stl_vector.h(75): here
            instantiation of class "std::_Vector_base<_Tp, _Alloc> [with _Tp=<error-type>, _Alloc=std::allocator<<error-type>>]" 
/usr/include/c++/4.8/bits/stl_vector.h(210): here
            instantiation of class "std::vector<_Tp, _Alloc> [with _Tp=<error-type>, _Alloc=std::allocator<<error-type>>]" 
sigmoid_partial_layer_tester_cuda.cu(77): here

/usr/include/c++/4.8/bits/ptr_traits.h(147): error: incomplete type is not allowed
          detected during:
            instantiation of type "std::pointer_traits<_Ptr>::rebind<const void> [with _Ptr=<error-type>]" 
/usr/include/c++/4.8/bits/alloc_traits.h(131): here
            instantiation of class "std::allocator_traits<_Alloc> [with _Alloc=std::allocator<<error-type>>]" 
/usr/include/c++/4.8/ext/alloc_traits.h(123): here
            instantiation of class "__gnu_cxx::__alloc_traits<_Alloc> [with _Alloc=std::allocator<<error-type>>]" 
/usr/include/c++/4.8/bits/stl_vector.h(75): here
            instantiation of class "std::_Vector_base<_Tp, _Alloc> [with _Tp=<error-type>, _Alloc=std::allocator<<error-type>>]" 
/usr/include/c++/4.8/bits/stl_vector.h(210): here
            instantiation of class "std::vector<_Tp, _Alloc> [with _Tp=<error-type>, _Alloc=std::allocator<<error-type>>]" 
sigmoid_partial_layer_tester_cuda.cu(77): here

/usr/include/c++/4.8/type_traits(1531): error: incomplete type is not allowed
          detected during:
            instantiation of class "std::make_unsigned<_Tp> [with _Tp=<error-type>]" 
/usr/include/c++/4.8/bits/alloc_traits.h(153): here
            instantiation of class "std::allocator_traits<_Alloc> [with _Alloc=std::allocator<<error-type>>]" 
/usr/include/c++/4.8/ext/alloc_traits.h(123): here
            instantiation of class "__gnu_cxx::__alloc_traits<_Alloc> [with _Alloc=std::allocator<<error-type>>]" 
/usr/include/c++/4.8/bits/stl_vector.h(75): here
            instantiation of class "std::_Vector_base<_Tp, _Alloc> [with _Tp=<error-type>, _Alloc=std::allocator<<error-type>>]" 
/usr/include/c++/4.8/bits/stl_vector.h(210): here
            instantiation of class "std::vector<_Tp, _Alloc> [with _Tp=<error-type>, _Alloc=std::allocator<<error-type>>]" 
sigmoid_partial_layer_tester_cuda.cu(77): here

/usr/include/c++/4.8/bits/alloc_traits.h(202): error: incomplete type is not allowed
          detected during:
            instantiation of type "std::allocator_traits<_Alloc>::rebind_alloc<<error-type>> [with _Alloc=std::allocator<<error-type>>]" 
/usr/include/c++/4.8/ext/alloc_traits.h(196): here
            instantiation of class "__gnu_cxx::__alloc_traits<_Alloc>::rebind<_Tp> [with _Alloc=std::allocator<<error-type>>, _Tp=<error-type>]" 
/usr/include/c++/4.8/bits/stl_vector.h(75): here
            instantiation of class "std::_Vector_base<_Tp, _Alloc> [with _Tp=<error-type>, _Alloc=std::allocator<<error-type>>]" 
/usr/include/c++/4.8/bits/stl_vector.h(210): here
            instantiation of class "std::vector<_Tp, _Alloc> [with _Tp=<error-type>, _Alloc=std::allocator<<error-type>>]" 
sigmoid_partial_layer_tester_cuda.cu(77): here

/usr/include/c++/4.8/bits/alloc_traits.h(90): error: name followed by "::" must be a class or namespace name
          detected during:
            instantiation of class "std::allocator_traits<_Alloc> [with _Alloc=<error-type>]" 
/usr/include/c++/4.8/ext/alloc_traits.h(123): here
            instantiation of class "__gnu_cxx::__alloc_traits<_Alloc> [with _Alloc=<error-type>]" 
/usr/include/c++/4.8/bits/stl_vector.h(76): here
            instantiation of class "std::_Vector_base<_Tp, _Alloc> [with _Tp=<error-type>, _Alloc=std::allocator<<error-type>>]" 
/usr/include/c++/4.8/bits/stl_vector.h(210): here
            instantiation of class "std::vector<_Tp, _Alloc> [with _Tp=<error-type>, _Alloc=std::allocator<<error-type>>]" 
sigmoid_partial_layer_tester_cuda.cu(77): here

/usr/include/c++/4.8/bits/stl_vector.h(80): error: not a class or struct name
          detected during:
            instantiation of class "std::_Vector_base<_Tp, _Alloc>::_Vector_impl [with _Tp=<error-type>, _Alloc=std::allocator<<error-type>>]" 
(164): here
            instantiation of class "std::_Vector_base<_Tp, _Alloc> [with _Tp=<error-type>, _Alloc=std::allocator<<error-type>>]" 
(210): here
            instantiation of class "std::vector<_Tp, _Alloc> [with _Tp=<error-type>, _Alloc=std::allocator<<error-type>>]" 
sigmoid_partial_layer_tester_cuda.cu(77): here

sigmoid_partial_layer_tester_cuda.cu(78): error: identifier "input_configuration_specific" is undefined

sigmoid_partial_layer_tester_cuda.cu(88): error: class "nnforge::sigmoid_layer" has no member "affected_feature_map_id_list"

23 errors detected in the compilation of "/tmp/tmpxft_0000701b_00000000-10_sigmoid_partial_layer_tester_cuda.compute_35.cpp1.ii".
make: *** [sigmoid_partial_layer_tester_cuda.o] Error 2

Also, I am running a debug build.

**Comment by milakov** [comment]
Hi,
Pull the latest version to get the bug with sigmoid_partial_layer_tester_cuda.cu fixed.
inc/ and lib64/ for cuDNN v3 is fixed as well.
Will look into other issue, but I have no troubles building with CPP11COMPILER =no with version similar to yours.

**Comment by anshumang** [comment]
Do you mean pull the [latest](https://github.com/milakov/nnForge/commit/1fbb821206ac5ba17cd922d83f0822472afa22f5) commit to master? Cloned the repo but getting the memcpy error below under nnforge/-
neuron_value_set.cpp: In member function ‘void nnforge::neuron_value_set::add_entry(const float*)’:
neuron_value_set.cpp:126:82: error: ‘memcpy’ was not declared in this scope
   memcpy(&neuron_value_list.back()->at(0), new_data, neuron_count * sizeof(float));

Also I have copied the log with CPP!!COMPILER=no to this [gist](https://gist.github.com/anshumang/82d7dca4e9fe9e5c7b79).

**Comment by anshumang** [comment]
reshape_data_transformer.cpp:43:84: error: ‘memcpy’ was not declared in this scope
   memcpy(data_transformed, data, original_config.get_neuron_count() * sizeof(float));
after the pull.

**Comment by anshumang** [comment]
[Here](https://github.com/milakov/nnForge/pull/27) is a PR that fixes the remaining missing <cstring> include.

**Comment by anshumang** [comment]
Bunch of linking errors related to protobuf when building examples/imagenet. Log [here](https://gist.github.com/anshumang/0bf6cc3586e689d212b0).
Missing anything obvious?

**Comment by milakov** [comment]
Merged your PR, thanks!
Link errors: This https://github.com/BVLC/caffe/issues/19 might be helpful. You probably include headers from newer protobuf version and link to older libraries?

**Comment by milakov** [comment]
Anshuman, did you solve protobuf link errors?

**Comment by anshumang** [comment]
Sorry have been sidetracked by some other work. I can give it another try tomorrow. Do you want me to close the issue now and reopen it if I face further issues?

**Comment by milakov** [comment]
That's fine, keep this oe opened. Thanks!

**Comment by anshumang** [comment]
:+1:

**Comment by anshumang** [comment]
examples/imagenet builds correctly with new install of protobuf, thanks !

**Comment by milakov** [comment]
Cool, thanks!
